apiVersion: apps/v1
kind: Job
metadata:
  name: spotify-crawler
spec:
  selector:
    matchLabels:
      app: spotify-crawler
  template:
    metadata:
      labels:
        app: spotify-crawler
    spec:
      containers:
        - name: spotify-crawler
          image:
          imagePullPolicy: Always
          volumeMounts:
            - name: youtube-audios-2
              mountPath:
      volumes:
        - name: youtube-audios-2
          persistentVolumeClaim:
            claimName: youtube-audios-2

      imagePullSecrets:
        - name: secret-gitlab
